CREATE USER C##SWIMPOOL IDENTIFIED BY SWIMPOOL;

GRANT CREATE SESSION TO C##SWIMPOOL;

GRANT CREATE TABLE TO C##SWIMPOOL;

GRANT CREATE SEQUENCE TO C##SWIMPOOL;

ALTER USER C##SWIMPOOL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

COMMIT;