CREATE USER C##MEMBER IDENTIFIED BY MEMBER;

GRANT CREATE SESSION TO C##MEMBER;

GRANT CREATE TABLE TO C##MEMBER;

GRANT CREATE SEQUENCE TO C##MEMBER;

ALTER USER C##MEMBER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

COMMIT;